version: '3.7'
services:
  frontend:
    build: ./UI
    container_name: frontend
    restart: always
    ports:
      - 5173:5173

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
      - mqtt_broker
    environment:
      - SPRING_MONGODB_DATABASE=snemdb
      - SPRING_MONGODB_HOST=mongodb_container
      - MQTT_HOST=mqtt_broker
      - XTEXT_HOST=xtext_backend
      - COMPILER_BASE_PROJECT_PATH=/compiler/base
      - COMPILER_BASE_PROJECT_INSERT_PATH=/main/sensors
      - COMPILER_PREBUILD_FOLDER=/compiler/prebuild
      - EXTERNAL_SERVER_URL=http://localhost:8080
      - EXTERNAL_BROKER_URL=mqtt://localhost:1883
      - EXTERNAL_FIRMWARE_UPGRADE_URL=https://192.168.2.106:8080/program/binary/initial-image.bin
      - EXTERNAL_WIFI_SSID=snem
      - EXTERNAL_WIFI_PASSWORD=snem
    command: "java -jar /app.jar"

  xtext_backend:
    build: ./xtext_project/org.example.helloweb.parent
    container_name: xtext_backend
    restart: always
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081

  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./backend/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb_container:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  satelitte_emulator_1:
    container_name: emulator_1
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=1
    depends_on:
      - mqtt_broker

  satelitte_emulator_2:
    container_name: emulator_2
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=2
    depends_on:
      - mqtt_broker

  satelitte_emulator_3:
    container_name: emulator_3
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=3
    depends_on:
      - mqtt_broker

  satelitte_emulator_4:
    container_name: emulator_4
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=4
    depends_on:
      - mqtt_broker
    
  satelitte_emulator_5:
    container_name: emulator_5
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=5
    depends_on:
      - mqtt_broker

  satelitte_emulator_6:
    container_name: emulator_6
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=6
    depends_on:
      - mqtt_broker

  satelitte_emulator_7:
    container_name: emulator_7
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    environment:
      - EMU_ID=7
    depends_on:
      - mqtt_broker
    deploy:
      mode: replicated
      replicas: 7

volumes:
  mongodb_data_container: