version: '3.7'
services:
  frontend:
    build: ./UI
    container_name: frontend
    restart: always
    ports:
      - 5173:5173

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
      - mqtt_broker
    environment:
      - SPRING_MONGODB_DATABASE=snemdb
      - SPRING_MONGODB_HOST=mongodb_container
      - MQTT_HOST=mqtt_broker
      - XTEXT_HOST=xtext_backend
      - COMPILER_BASE_PROJECT_PATH=/compiler/base
      - COMPILER_BASE_PROJECT_INSERT_PATH=/main
    command: "java -jar /app.jar"
    volumes:
      - ./ESP-OTA-MQTT:/compiler/base

  xtext_backend:
    build: ./xtext_project/org.example.helloweb.parent
    container_name: xtext_backend
    restart: always
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081

  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./backend/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb_container:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  satelitte_emulator:
    build: ./emulator
    restart: always
    volumes:
      - ./emulator:/usr/src/app
    depends_on:
      - mqtt_broker

volumes:
  mongodb_data_container: