/**
 * SNEM API
 * Documentation for SNEM API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BinaryCompileResult {
    'compileErrors'?: string;
    'compileFailed'?: boolean;
    'compileOutput'?: string;
    'compileTime'?: Date;
    'deviceTypeId'?: string;
    'id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compileErrors",
            "baseName": "compileErrors",
            "type": "string",
            "format": ""
        },
        {
            "name": "compileFailed",
            "baseName": "compileFailed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "compileOutput",
            "baseName": "compileOutput",
            "type": "string",
            "format": ""
        },
        {
            "name": "compileTime",
            "baseName": "compileTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deviceTypeId",
            "baseName": "deviceTypeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BinaryCompileResult.attributeTypeMap;
    }

    public constructor() {
    }
}

