/**
 * SNEM API
 * Documentation for SNEM API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogType } from '../models/LogType';
import { HttpFile } from '../http/http';

export class LogMetadata {
    'id'?: string;
    'message'?: string;
    'satelliteId'?: string;
    'timestamp'?: Date;
    'type'?: LogType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "satelliteId",
            "baseName": "satelliteId",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "LogType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}



