/**
 * SNEM API
 * Documentation for SNEM API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProgramDslContent {
    'dslText'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dslText",
            "baseName": "dslText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProgramDslContent.attributeTypeMap;
    }

    public constructor() {
    }
}

