/**
 * SNEM API
 * Documentation for SNEM API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ProgramStatus {
    Unchanged = 'UNCHANGED',
    Changed = 'CHANGED',
    GeneratingCode = 'GENERATING_CODE',
    ErrorGeneratingCode = 'ERROR_GENERATING_CODE',
    CodeGenerated = 'CODE_GENERATED',
    CodeGeneratedRequiresOverride = 'CODE_GENERATED_REQUIRES_OVERRIDE',
    CompilingBinaries = 'COMPILING_BINARIES',
    ErrorCompilingBinaries = 'ERROR_COMPILING_BINARIES',
    CompiledCompletely = 'COMPILED_COMPLETELY',
    ErrorUnexpected = 'ERROR_UNEXPECTED'
}
