/**
 * SNEM API
 * Documentation for SNEM API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AreaMetadata } from '../models/AreaMetadata';
import { DeviceTypeMetadata } from '../models/DeviceTypeMetadata';
import { SatelliteStatus } from '../models/SatelliteStatus';
import { HttpFile } from '../http/http';

export class SatelliteMetadata {
    'area'?: AreaMetadata;
    'deviceTypeMetadata'?: DeviceTypeMetadata;
    'id'?: string;
    'name'?: string;
    'status'?: SatelliteStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "area",
            "baseName": "area",
            "type": "AreaMetadata",
            "format": ""
        },
        {
            "name": "deviceTypeMetadata",
            "baseName": "deviceTypeMetadata",
            "type": "DeviceTypeMetadata",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SatelliteStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SatelliteMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}



