/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HelloWebStandaloneSetup extends HelloWebStandaloneSetupGenerated {

	public static void doSetup() {
		new HelloWebStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
