/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.helloweb.HelloWebRuntimeModule;
import org.example.helloweb.HelloWebStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HelloWebIdeSetup extends HelloWebStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloWebRuntimeModule(), new HelloWebIdeModule()));
	}
	
}
