/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.helloweb.ui.internal.HellowebActivator;

public class HelloWebUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HellowebActivator.getInstance().getInjector("org.example.helloweb.HelloWeb");
	}

}
