/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.helloweb.HelloWebRuntimeModule;
import org.example.helloweb.HelloWebStandaloneSetup;
import org.example.helloweb.ide.HelloWebIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class HelloWebWebSetup extends HelloWebStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HelloWebRuntimeModule(), new HelloWebIdeModule(), new HelloWebWebModule()));
	}
	
}
