/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link HelloWebWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractHelloWebWebModule extends DefaultWebModule {

}
