/*
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.validation;

import org.eclipse.xtext.validation.Check;
import org.example.helloweb.helloWeb.SensorConfig;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class HelloWebValidator extends AbstractHelloWebValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					HelloWebPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	 @Check
	 public void checkWhateverIsMapped(SensorConfig sensorConfig) {
		 
	 }
	 
}
