/**
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.helloweb.helloWeb.Comparison#getLeft <em>Left</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Comparison#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.example.helloweb.helloWeb.HelloWebPackage#getComparison()
 * @model
 * @generated
 */
public interface Comparison extends Condition
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ComparisonValue)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getComparison_Left()
   * @model containment="true"
   * @generated
   */
  ComparisonValue getLeft();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Comparison#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ComparisonValue value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ComparisonValue)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getComparison_Right()
   * @model containment="true"
   * @generated
   */
  ComparisonValue getRight();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Comparison#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ComparisonValue value);

} // Comparison
