/**
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decimal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.helloweb.helloWeb.Decimal#getLeft <em>Left</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Decimal#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.example.helloweb.helloWeb.HelloWebPackage#getDecimal()
 * @model
 * @generated
 */
public interface Decimal extends ComparisonValue
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(int)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getDecimal_Left()
   * @model
   * @generated
   */
  int getLeft();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Decimal#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(int value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(int)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getDecimal_Right()
   * @model
   * @generated
   */
  int getRight();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Decimal#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(int value);

} // Decimal
