/**
 * generated by Xtext 2.31.0
 */
package org.example.helloweb.helloWeb;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.helloweb.helloWeb.HelloWebFactory
 * @model kind="package"
 * @generated
 */
public interface HelloWebPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "helloWeb";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/helloweb/HelloWeb";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "helloWeb";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HelloWebPackage eINSTANCE = org.example.helloweb.helloWeb.impl.HelloWebPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.SensorConfigImpl <em>Sensor Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.SensorConfigImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorConfig()
   * @generated
   */
  int SENSOR_CONFIG = 0;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_CONFIG__SENSORS = 0;

  /**
   * The feature id for the '<em><b>Device Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_CONFIG__DEVICE_TYPES = 1;

  /**
   * The number of structural features of the '<em>Sensor Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_CONFIG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.SensorImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Units</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__UNITS = 1;

  /**
   * The feature id for the '<em><b>Reader</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__READER = 2;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PINS = 3;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__OUT = 4;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.DeviceTypeImpl <em>Device Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.DeviceTypeImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getDeviceType()
   * @generated
   */
  int DEVICE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor Instantiations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__SENSOR_INSTANTIATIONS = 1;

  /**
   * The feature id for the '<em><b>Batch Rate Policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__BATCH_RATE_POLICY = 2;

  /**
   * The feature id for the '<em><b>Batch Size Policy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__BATCH_SIZE_POLICY = 3;

  /**
   * The feature id for the '<em><b>Heart Beat Policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__HEART_BEAT_POLICY = 4;

  /**
   * The number of structural features of the '<em>Device Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.SensorInstantiationImpl <em>Sensor Instantiation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.SensorInstantiationImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorInstantiation()
   * @generated
   */
  int SENSOR_INSTANTIATION = 3;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION__SENSOR = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION__NAME = 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION__PINS = 2;

  /**
   * The feature id for the '<em><b>Sampling Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION__SAMPLING_RATE = 3;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION__CONSTRAINTS = 4;

  /**
   * The number of structural features of the '<em>Sensor Instantiation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_INSTANTIATION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.ConstraintImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 4;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Sampling Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__SAMPLING_RATE = 1;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.ConditionImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OPERATOR = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.NestedLogicalConditionImpl <em>Nested Logical Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.NestedLogicalConditionImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getNestedLogicalCondition()
   * @generated
   */
  int NESTED_LOGICAL_CONDITION = 6;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_LOGICAL_CONDITION__OPERATOR = CONDITION__OPERATOR;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_LOGICAL_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_LOGICAL_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Nested Logical Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_LOGICAL_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.ComparisonImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 7;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OPERATOR = CONDITION__OPERATOR;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.ComparisonValueImpl <em>Comparison Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.ComparisonValueImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getComparisonValue()
   * @generated
   */
  int COMPARISON_VALUE = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Comparison Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.ValueRefImpl <em>Value Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.ValueRefImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getValueRef()
   * @generated
   */
  int VALUE_REF = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_REF__VALUE = COMPARISON_VALUE__VALUE;

  /**
   * The feature id for the '<em><b>Sensor Instantiation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_REF__SENSOR_INSTANTIATION = COMPARISON_VALUE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Out</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_REF__OUT = COMPARISON_VALUE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Value Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_REF_FEATURE_COUNT = COMPARISON_VALUE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.OutputImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.PinImpl <em>Pin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.PinImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getPin()
   * @generated
   */
  int PIN = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN__NAME = 0;

  /**
   * The number of structural features of the '<em>Pin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.SensorUnitImpl <em>Sensor Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.SensorUnitImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorUnit()
   * @generated
   */
  int SENSOR_UNIT = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_UNIT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Sensor Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_UNIT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.TimeUnitImpl <em>Time Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.TimeUnitImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_UNIT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_UNIT__UNIT = 1;

  /**
   * The number of structural features of the '<em>Time Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_UNIT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.helloweb.helloWeb.impl.DecimalImpl <em>Decimal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.helloweb.helloWeb.impl.DecimalImpl
   * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getDecimal()
   * @generated
   */
  int DECIMAL = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL__VALUE = COMPARISON_VALUE__VALUE;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL__LEFT = COMPARISON_VALUE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL__RIGHT = COMPARISON_VALUE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Decimal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL_FEATURE_COUNT = COMPARISON_VALUE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.SensorConfig <em>Sensor Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Config</em>'.
   * @see org.example.helloweb.helloWeb.SensorConfig
   * @generated
   */
  EClass getSensorConfig();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.SensorConfig#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see org.example.helloweb.helloWeb.SensorConfig#getSensors()
   * @see #getSensorConfig()
   * @generated
   */
  EReference getSensorConfig_Sensors();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.SensorConfig#getDeviceTypes <em>Device Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Device Types</em>'.
   * @see org.example.helloweb.helloWeb.SensorConfig#getDeviceTypes()
   * @see #getSensorConfig()
   * @generated
   */
  EReference getSensorConfig_DeviceTypes();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.example.helloweb.helloWeb.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.helloweb.helloWeb.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.Sensor#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Units</em>'.
   * @see org.example.helloweb.helloWeb.Sensor#getUnits()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Units();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Sensor#getReader <em>Reader</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reader</em>'.
   * @see org.example.helloweb.helloWeb.Sensor#getReader()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Reader();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.Sensor#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pins</em>'.
   * @see org.example.helloweb.helloWeb.Sensor#getPins()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Pins();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.Sensor#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Out</em>'.
   * @see org.example.helloweb.helloWeb.Sensor#getOut()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Out();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.DeviceType <em>Device Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Type</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType
   * @generated
   */
  EClass getDeviceType();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.DeviceType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType#getName()
   * @see #getDeviceType()
   * @generated
   */
  EAttribute getDeviceType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.DeviceType#getSensorInstantiations <em>Sensor Instantiations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensor Instantiations</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType#getSensorInstantiations()
   * @see #getDeviceType()
   * @generated
   */
  EReference getDeviceType_SensorInstantiations();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.DeviceType#getBatchRatePolicy <em>Batch Rate Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Batch Rate Policy</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType#getBatchRatePolicy()
   * @see #getDeviceType()
   * @generated
   */
  EReference getDeviceType_BatchRatePolicy();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.DeviceType#getBatchSizePolicy <em>Batch Size Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Batch Size Policy</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType#getBatchSizePolicy()
   * @see #getDeviceType()
   * @generated
   */
  EAttribute getDeviceType_BatchSizePolicy();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.DeviceType#getHeartBeatPolicy <em>Heart Beat Policy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Heart Beat Policy</em>'.
   * @see org.example.helloweb.helloWeb.DeviceType#getHeartBeatPolicy()
   * @see #getDeviceType()
   * @generated
   */
  EReference getDeviceType_HeartBeatPolicy();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.SensorInstantiation <em>Sensor Instantiation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Instantiation</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation
   * @generated
   */
  EClass getSensorInstantiation();

  /**
   * Returns the meta object for the reference '{@link org.example.helloweb.helloWeb.SensorInstantiation#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation#getSensor()
   * @see #getSensorInstantiation()
   * @generated
   */
  EReference getSensorInstantiation_Sensor();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.SensorInstantiation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation#getName()
   * @see #getSensorInstantiation()
   * @generated
   */
  EAttribute getSensorInstantiation_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.example.helloweb.helloWeb.SensorInstantiation#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pins</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation#getPins()
   * @see #getSensorInstantiation()
   * @generated
   */
  EAttribute getSensorInstantiation_Pins();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.SensorInstantiation#getSamplingRate <em>Sampling Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sampling Rate</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation#getSamplingRate()
   * @see #getSensorInstantiation()
   * @generated
   */
  EReference getSensorInstantiation_SamplingRate();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.helloweb.helloWeb.SensorInstantiation#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.example.helloweb.helloWeb.SensorInstantiation#getConstraints()
   * @see #getSensorInstantiation()
   * @generated
   */
  EReference getSensorInstantiation_Constraints();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.example.helloweb.helloWeb.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.Constraint#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.example.helloweb.helloWeb.Constraint#getCondition()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Condition();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.Constraint#getSamplingRate <em>Sampling Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sampling Rate</em>'.
   * @see org.example.helloweb.helloWeb.Constraint#getSamplingRate()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_SamplingRate();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.example.helloweb.helloWeb.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Condition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.example.helloweb.helloWeb.Condition#getOperator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Operator();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.NestedLogicalCondition <em>Nested Logical Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nested Logical Condition</em>'.
   * @see org.example.helloweb.helloWeb.NestedLogicalCondition
   * @generated
   */
  EClass getNestedLogicalCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.NestedLogicalCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.example.helloweb.helloWeb.NestedLogicalCondition#getLeft()
   * @see #getNestedLogicalCondition()
   * @generated
   */
  EReference getNestedLogicalCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.NestedLogicalCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.example.helloweb.helloWeb.NestedLogicalCondition#getRight()
   * @see #getNestedLogicalCondition()
   * @generated
   */
  EReference getNestedLogicalCondition_Right();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see org.example.helloweb.helloWeb.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.Comparison#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.example.helloweb.helloWeb.Comparison#getLeft()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.example.helloweb.helloWeb.Comparison#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.example.helloweb.helloWeb.Comparison#getRight()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Right();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.ComparisonValue <em>Comparison Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison Value</em>'.
   * @see org.example.helloweb.helloWeb.ComparisonValue
   * @generated
   */
  EClass getComparisonValue();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.ComparisonValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.example.helloweb.helloWeb.ComparisonValue#getValue()
   * @see #getComparisonValue()
   * @generated
   */
  EAttribute getComparisonValue_Value();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.ValueRef <em>Value Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Ref</em>'.
   * @see org.example.helloweb.helloWeb.ValueRef
   * @generated
   */
  EClass getValueRef();

  /**
   * Returns the meta object for the reference '{@link org.example.helloweb.helloWeb.ValueRef#getSensorInstantiation <em>Sensor Instantiation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor Instantiation</em>'.
   * @see org.example.helloweb.helloWeb.ValueRef#getSensorInstantiation()
   * @see #getValueRef()
   * @generated
   */
  EReference getValueRef_SensorInstantiation();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.ValueRef#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Out</em>'.
   * @see org.example.helloweb.helloWeb.ValueRef#getOut()
   * @see #getValueRef()
   * @generated
   */
  EAttribute getValueRef_Out();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.example.helloweb.helloWeb.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Output#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.helloweb.helloWeb.Output#getName()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Name();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Pin <em>Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pin</em>'.
   * @see org.example.helloweb.helloWeb.Pin
   * @generated
   */
  EClass getPin();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Pin#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.helloweb.helloWeb.Pin#getName()
   * @see #getPin()
   * @generated
   */
  EAttribute getPin_Name();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.SensorUnit <em>Sensor Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Unit</em>'.
   * @see org.example.helloweb.helloWeb.SensorUnit
   * @generated
   */
  EClass getSensorUnit();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.SensorUnit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.example.helloweb.helloWeb.SensorUnit#getValue()
   * @see #getSensorUnit()
   * @generated
   */
  EAttribute getSensorUnit_Value();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Unit</em>'.
   * @see org.example.helloweb.helloWeb.TimeUnit
   * @generated
   */
  EClass getTimeUnit();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.TimeUnit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.example.helloweb.helloWeb.TimeUnit#getValue()
   * @see #getTimeUnit()
   * @generated
   */
  EAttribute getTimeUnit_Value();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.TimeUnit#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see org.example.helloweb.helloWeb.TimeUnit#getUnit()
   * @see #getTimeUnit()
   * @generated
   */
  EAttribute getTimeUnit_Unit();

  /**
   * Returns the meta object for class '{@link org.example.helloweb.helloWeb.Decimal <em>Decimal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decimal</em>'.
   * @see org.example.helloweb.helloWeb.Decimal
   * @generated
   */
  EClass getDecimal();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Decimal#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see org.example.helloweb.helloWeb.Decimal#getLeft()
   * @see #getDecimal()
   * @generated
   */
  EAttribute getDecimal_Left();

  /**
   * Returns the meta object for the attribute '{@link org.example.helloweb.helloWeb.Decimal#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see org.example.helloweb.helloWeb.Decimal#getRight()
   * @see #getDecimal()
   * @generated
   */
  EAttribute getDecimal_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HelloWebFactory getHelloWebFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.SensorConfigImpl <em>Sensor Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.SensorConfigImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorConfig()
     * @generated
     */
    EClass SENSOR_CONFIG = eINSTANCE.getSensorConfig();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_CONFIG__SENSORS = eINSTANCE.getSensorConfig_Sensors();

    /**
     * The meta object literal for the '<em><b>Device Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_CONFIG__DEVICE_TYPES = eINSTANCE.getSensorConfig_DeviceTypes();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.SensorImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__UNITS = eINSTANCE.getSensor_Units();

    /**
     * The meta object literal for the '<em><b>Reader</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__READER = eINSTANCE.getSensor_Reader();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__PINS = eINSTANCE.getSensor_Pins();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__OUT = eINSTANCE.getSensor_Out();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.DeviceTypeImpl <em>Device Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.DeviceTypeImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getDeviceType()
     * @generated
     */
    EClass DEVICE_TYPE = eINSTANCE.getDeviceType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_TYPE__NAME = eINSTANCE.getDeviceType_Name();

    /**
     * The meta object literal for the '<em><b>Sensor Instantiations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_TYPE__SENSOR_INSTANTIATIONS = eINSTANCE.getDeviceType_SensorInstantiations();

    /**
     * The meta object literal for the '<em><b>Batch Rate Policy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_TYPE__BATCH_RATE_POLICY = eINSTANCE.getDeviceType_BatchRatePolicy();

    /**
     * The meta object literal for the '<em><b>Batch Size Policy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_TYPE__BATCH_SIZE_POLICY = eINSTANCE.getDeviceType_BatchSizePolicy();

    /**
     * The meta object literal for the '<em><b>Heart Beat Policy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_TYPE__HEART_BEAT_POLICY = eINSTANCE.getDeviceType_HeartBeatPolicy();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.SensorInstantiationImpl <em>Sensor Instantiation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.SensorInstantiationImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorInstantiation()
     * @generated
     */
    EClass SENSOR_INSTANTIATION = eINSTANCE.getSensorInstantiation();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_INSTANTIATION__SENSOR = eINSTANCE.getSensorInstantiation_Sensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_INSTANTIATION__NAME = eINSTANCE.getSensorInstantiation_Name();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_INSTANTIATION__PINS = eINSTANCE.getSensorInstantiation_Pins();

    /**
     * The meta object literal for the '<em><b>Sampling Rate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_INSTANTIATION__SAMPLING_RATE = eINSTANCE.getSensorInstantiation_SamplingRate();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_INSTANTIATION__CONSTRAINTS = eINSTANCE.getSensorInstantiation_Constraints();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.ConstraintImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__CONDITION = eINSTANCE.getConstraint_Condition();

    /**
     * The meta object literal for the '<em><b>Sampling Rate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__SAMPLING_RATE = eINSTANCE.getConstraint_SamplingRate();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.ConditionImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__OPERATOR = eINSTANCE.getCondition_Operator();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.NestedLogicalConditionImpl <em>Nested Logical Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.NestedLogicalConditionImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getNestedLogicalCondition()
     * @generated
     */
    EClass NESTED_LOGICAL_CONDITION = eINSTANCE.getNestedLogicalCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_LOGICAL_CONDITION__LEFT = eINSTANCE.getNestedLogicalCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_LOGICAL_CONDITION__RIGHT = eINSTANCE.getNestedLogicalCondition_Right();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.ComparisonImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__LEFT = eINSTANCE.getComparison_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__RIGHT = eINSTANCE.getComparison_Right();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.ComparisonValueImpl <em>Comparison Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.ComparisonValueImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getComparisonValue()
     * @generated
     */
    EClass COMPARISON_VALUE = eINSTANCE.getComparisonValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON_VALUE__VALUE = eINSTANCE.getComparisonValue_Value();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.ValueRefImpl <em>Value Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.ValueRefImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getValueRef()
     * @generated
     */
    EClass VALUE_REF = eINSTANCE.getValueRef();

    /**
     * The meta object literal for the '<em><b>Sensor Instantiation</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_REF__SENSOR_INSTANTIATION = eINSTANCE.getValueRef_SensorInstantiation();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE_REF__OUT = eINSTANCE.getValueRef_Out();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.OutputImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__NAME = eINSTANCE.getOutput_Name();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.PinImpl <em>Pin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.PinImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getPin()
     * @generated
     */
    EClass PIN = eINSTANCE.getPin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIN__NAME = eINSTANCE.getPin_Name();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.SensorUnitImpl <em>Sensor Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.SensorUnitImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getSensorUnit()
     * @generated
     */
    EClass SENSOR_UNIT = eINSTANCE.getSensorUnit();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_UNIT__VALUE = eINSTANCE.getSensorUnit_Value();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.TimeUnitImpl <em>Time Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.TimeUnitImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getTimeUnit()
     * @generated
     */
    EClass TIME_UNIT = eINSTANCE.getTimeUnit();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_UNIT__VALUE = eINSTANCE.getTimeUnit_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_UNIT__UNIT = eINSTANCE.getTimeUnit_Unit();

    /**
     * The meta object literal for the '{@link org.example.helloweb.helloWeb.impl.DecimalImpl <em>Decimal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.helloweb.helloWeb.impl.DecimalImpl
     * @see org.example.helloweb.helloWeb.impl.HelloWebPackageImpl#getDecimal()
     * @generated
     */
    EClass DECIMAL = eINSTANCE.getDecimal();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECIMAL__LEFT = eINSTANCE.getDecimal_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECIMAL__RIGHT = eINSTANCE.getDecimal_Right();

  }

} //HelloWebPackage
