/**
 * generated by Xtext 2.33.0
 */
package org.example.helloweb.helloWeb;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.helloweb.helloWeb.Sensor#getName <em>Name</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Sensor#getUnits <em>Units</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Sensor#getReader <em>Reader</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Sensor#getPins <em>Pins</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.Sensor#getOut <em>Out</em>}</li>
 * </ul>
 *
 * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Sensor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Units</b></em>' containment reference list.
   * The list contents are of type {@link org.example.helloweb.helloWeb.SensorUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' containment reference list.
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor_Units()
   * @model containment="true"
   * @generated
   */
  EList<SensorUnit> getUnits();

  /**
   * Returns the value of the '<em><b>Reader</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reader</em>' attribute.
   * @see #setReader(String)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor_Reader()
   * @model
   * @generated
   */
  String getReader();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.Sensor#getReader <em>Reader</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reader</em>' attribute.
   * @see #getReader()
   * @generated
   */
  void setReader(String value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' containment reference list.
   * The list contents are of type {@link org.example.helloweb.helloWeb.Pin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' containment reference list.
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor_Pins()
   * @model containment="true"
   * @generated
   */
  EList<Pin> getPins();

  /**
   * Returns the value of the '<em><b>Out</b></em>' containment reference list.
   * The list contents are of type {@link org.example.helloweb.helloWeb.Output}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' containment reference list.
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getSensor_Out()
   * @model containment="true"
   * @generated
   */
  EList<Output> getOut();

} // Sensor
