/**
 * generated by Xtext 2.31.0
 */
package org.example.helloweb.helloWeb;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.helloweb.helloWeb.TimeUnit#getValue <em>Value</em>}</li>
 *   <li>{@link org.example.helloweb.helloWeb.TimeUnit#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.example.helloweb.helloWeb.HelloWebPackage#getTimeUnit()
 * @model
 * @generated
 */
public interface TimeUnit extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getTimeUnit_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.TimeUnit#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see org.example.helloweb.helloWeb.HelloWebPackage#getTimeUnit_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link org.example.helloweb.helloWeb.TimeUnit#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // TimeUnit
